image:
  - Visual Studio 2019
clone_folder: c:\projects\source

build_script:
- cmd: >-
    mkdir build

    cd build

    set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts

    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Debug

